[default]
# project
src = 'src'
test = 'src/test'
out = 'out'
libs = ['lib']
remappings = ['ds-test=lib/ds-test/src/', '@openzeppelin=lib/openzeppelin-contracts/contracts/','solmate/=lib/solmate/src/']
cache = true
solc_version = '0.8.10'
optimizer = true
optimizer_runs = 500
# tests
chain_id = 1
fuzz_runs = 1024
gas_reports = ['*']
no_storage_caching = false
rpc_storage_caching = { chains = 'all', endpoints = 'remote' }

